# Generated by Django 3.1.5 on 2021-01-15 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=10, verbose_name='Название факультета')),
                ('faculty_number', models.IntegerField(verbose_name='Номер факультета')),
                ('faculty_info', models.CharField(max_length=200, verbose_name='Информация о факультете')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(default='0000', max_length=10, verbose_name='Номер группы')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('lecturer_name_surname', models.CharField(max_length=100, verbose_name='ФИО лектора')),
                ('practice_name_surname', models.CharField(max_length=100, verbose_name='Фио преподавателя практики')),
                ('grading_method', models.CharField(default='Стандартный', max_length=30, verbose_name='Метод оценивания')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_count', models.IntegerField(default=0, verbose_name='Количество семестров')),
                ('subjects', models.CharField(max_length=200, verbose_name='Тут переделать')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(default='Пупкин Вася Станиславович', max_length=50, verbose_name='ФИО')),
                ('birthday', models.CharField(default='01.01.1800', max_length=15, verbose_name='ДР')),
                ('is_foreigner', models.BooleanField(default=0, verbose_name='Является ли иностранцем')),
                ('is_expelled', models.BooleanField(default=0, verbose_name='Является ли отчисленным')),
                ('Group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_work.group')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField(default=0, verbose_name='Номер семестра')),
                ('start_date', models.CharField(default='01.01.1800', max_length=10, verbose_name='Дата начала семестра')),
                ('stop_date', models.CharField(default='01.01.1800', max_length=10, verbose_name='Дата окончания семестра')),
                ('TeachingPlan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_work.teachingplan')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='teaching_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_work.teachingplan'),
        ),
    ]
