# Generated by Django 3.1.5 on 2021-01-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_work', '0002_auto_20210115_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_number',
            field=models.IntegerField(default=0, verbose_name='Номер факультета'),
        ),
    ]
