# Generated by Django 3.1.5 on 2021-01-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_work', '0004_group_faculty_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingplan',
            old_name='subjects',
            new_name='disciplines',
        ),
        migrations.AddField(
            model_name='teachingplan',
            name='number',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер учебного плана'),
        ),
    ]
