# Generated by Django 3.1.5 on 2021-01-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_work', '0005_auto_20210115_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Faculty_FK',
            field=models.IntegerField(default=0, verbose_name='Номер факультета'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teaching_plan',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер учебного плана'),
        ),
    ]
