# Generated by Django 3.1.5 on 2021-01-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_work', '0006_auto_20210117_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Group_id',
        ),
        migrations.AddField(
            model_name='student',
            name='Group_num',
            field=models.CharField(default='0000', max_length=10, verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(),
        ),
    ]
