# Generated by Django 3.1.5 on 2021-01-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_work', '0007_auto_20210117_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_foreigner',
            field=models.BooleanField(verbose_name='Является ли иностранцем'),
        ),
    ]
