# Generated by Django 3.1.5 on 2021-01-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_work', '0008_auto_20210117_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_expelled',
            field=models.BooleanField(null=True, verbose_name='Является ли отчисленным'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_foreigner',
            field=models.BooleanField(null=True, verbose_name='Является ли иностранцем'),
        ),
    ]
