# Generated by Django 3.1.5 on 2021-01-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_work', '0010_auto_20210118_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.CharField(default='0000', max_length=10, verbose_name='Номер группы'),
        ),
    ]
